### ISSUE TITLE
[battery]: allow to show percentage

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-general#45]
default can be icon only, but there should be an option to also show "icon + number percentage" as option

**Comment by davidedmundson** [comment]
side by side or as an overlay?

**Comment by llelectronics** [comment]
how about dynamically. If there is enough space to fit it as overlay ontop of the icon then there otherwise beside the icon itself. (or make it configurable for the user)

**Comment by davidedmundson** [comment]
In the system tray, all applets are forced to be square.
(I'm not saying it should do that, but that's what it currently does and Marco is weirdly obsessed with that)

The battery by default is in the system tray. Though it can also be placed outside that.

**Comment by star-buck** [comment]
how about the option to show percentage and keep it squared:
doing a circle outline which shrinks from 360° - 0° for visual and place %number inside

**Comment by notmart** [comment]
I can try to make possible for the systray to have non square items, i fear about layouting issues as it makes the logic more complicated, but we can see how it works

**Comment by star-buck** [comment]
But how about the circle percentage option, that is squared.

**Comment by notmart** [comment]
a quick and dirty experiment with text and circle
![spectacle tj5251](https://cloud.githubusercontent.com/assets/4526371/20893883/a95ae9c4-bb13-11e6-9bc4-978ff3afe422.png)
it works, but may look a bit crammed and is not immediately recognizable as a battery. Width different dpi values on high-res screens the visual result may vary 
an alternative is something that looks similar to what the telegram icon is doing there for unread messages (also, code-wise would be much simpler, so more maintainable):
![spectacle jh5950](https://cloud.githubusercontent.com/assets/4526371/20894681/b4f6d146-bb16-11e6-8cfe-d9764f68ac89.png)
or, perhaps inverted:
![spectacle th6091](https://cloud.githubusercontent.com/assets/4526371/20894757/f624cb96-bb16-11e6-8d92-82c5f5f01719.png)
on higher dpi screens should look a bit more readable

**Comment by star-buck** [comment]
And how does it look when placing the percentage in the battery symbol? So
its either just the percentage or the gfx inside the battery.

**Comment by star-buck** [comment]
Non-inverted then, inverted always looks "full".

**Comment by notmart** [comment]
another one, this is how would look if the systray allows non square items, so the percentage besides the icon (still a lot of hardcoded values to make it look right, would have to be implemented properly)
![spectacle vs5081](https://cloud.githubusercontent.com/assets/4526371/20895394/91ce2aae-bb19-11e6-99a1-126c2e523b45.png)

with the text inside the battery it would look fine (perhaps a problem for the green plug that says it's pluged in), but the problem would be that would be dependent of the breeze plasma theme, as different themes can have a differently styled battery, so overlaying the text to the battery outside may or may not work with 3rd party themes

**Comment by star-buck** [comment]
I would go with the non-inverted overlay then, its squared and possibly
works with most themes (i still like the circle best, maybe do that as an
option, so you would have battery, battery percentage, percentage circle to
choose from and all are squared).

**Comment by notmart** [comment]
an option to enable a label on bottom-right is in master, should appear in neon devel shortly

**Comment by star-buck** [comment]
after testing it now in kde neon live, i would suggest to put the percentage inside the battery and remove the "%", so just the number. Then put the charging symbol as small overlay in lower right corner.
